---
- name: Disk Cleanup
  hosts: all
  become: true
  gather_facts: true
  vars:
    clean_logs_older_than_days: 30
    clean_tmp: true
    clean_package_cache: true
    clean_journal: true
    journal_vacuum_size: "500M"
    
  tasks:
    - name: Get disk usage before cleanup
      ansible.builtin.shell: df -h / | tail -1 | awk "{print \$4}"
      register: disk_before
      changed_when: false

    - name: Clean old log files
      ansible.builtin.shell: |
        find /var/log -type f -name "*.log" -mtime +{{ clean_logs_older_than_days }} -delete 2>/dev/null || true
        find /var/log -type f -name "*.gz" -mtime +{{ clean_logs_older_than_days }} -delete 2>/dev/null || true
        find /var/log -type f -name "*.[0-9]" -mtime +{{ clean_logs_older_than_days }} -delete 2>/dev/null || true
      changed_when: false

    - name: Clean temporary files
      ansible.builtin.shell: |
        find /tmp -type f -atime +7 -delete 2>/dev/null || true
        find /var/tmp -type f -atime +7 -delete 2>/dev/null || true
      when: clean_tmp | bool
      changed_when: false

    - name: Clean apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        autoclean: yes
        autoremove: yes
      when:
        - ansible_os_family == "Debian"
        - clean_package_cache | bool

    - name: Clean dnf cache (RHEL/CentOS)
      ansible.builtin.shell: dnf clean all
      when:
        - ansible_os_family == "RedHat"
        - clean_package_cache | bool
      changed_when: false

    - name: Vacuum systemd journal
      ansible.builtin.shell: journalctl --vacuum-size={{ journal_vacuum_size }}
      when: clean_journal | bool
      changed_when: false
      failed_when: false

    - name: Clean old kernels (RHEL/CentOS)
      ansible.builtin.shell: dnf remove --oldinstallonly --setopt installonly_limit=2 -y
      when: ansible_os_family == "RedHat"
      failed_when: false
      changed_when: false

    - name: Get disk usage after cleanup
      ansible.builtin.shell: df -h / | tail -1 | awk "{print \$4}"
      register: disk_after
      changed_when: false

    - name: Display cleanup results
      ansible.builtin.debug:
        msg: |
          Disk space before cleanup: {{ disk_before.stdout }}
          Disk space after cleanup: {{ disk_after.stdout }}
