---
- name: Docker Management
  hosts: all
  become: true
  gather_facts: true
  vars:
    docker_action: "status"  # install, status, prune, start, stop
    docker_users: []  # users to add to docker group
    
  tasks:
    - name: Install Docker (RHEL/CentOS)
      block:
        - name: Install required packages
          ansible.builtin.dnf:
            name:
              - dnf-plugins-core
            state: present

        - name: Add Docker repository
          ansible.builtin.shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          args:
            creates: /etc/yum.repos.d/docker-ce.repo

        - name: Install Docker packages
          ansible.builtin.dnf:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present

        - name: Start and enable Docker
          ansible.builtin.service:
            name: docker
            state: started
            enabled: yes
      when:
        - docker_action == "install"
        - ansible_os_family == "RedHat"

    - name: Install Docker (Debian/Ubuntu)
      block:
        - name: Install prerequisites
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
            state: present
            update_cache: yes

        - name: Add Docker GPG key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository
          ansible.builtin.apt_repository:
            repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present

        - name: Install Docker packages
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
            update_cache: yes

        - name: Start and enable Docker
          ansible.builtin.service:
            name: docker
            state: started
            enabled: yes
      when:
        - docker_action == "install"
        - ansible_os_family == "Debian"

    - name: Add users to docker group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: "{{ docker_users }}"
      when: docker_users | length > 0

    - name: Get Docker status
      ansible.builtin.shell: |
        echo "=== Docker Version ==="
        docker version --format "Client: {{.Client.Version}}, Server: {{.Server.Version}}" 2>/dev/null || echo "Docker not running"
        echo ""
        echo "=== Running Containers ==="
        docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}" 2>/dev/null || echo "None"
        echo ""
        echo "=== Disk Usage ==="
        docker system df 2>/dev/null || echo "N/A"
      register: docker_status
      changed_when: false
      failed_when: false
      when: docker_action == "status"

    - name: Display Docker status
      ansible.builtin.debug:
        msg: "{{ docker_status.stdout_lines }}"
      when: docker_action == "status"

    - name: Prune Docker resources
      ansible.builtin.shell: |
        docker system prune -af --volumes
        docker builder prune -af
      when: docker_action == "prune"
      register: prune_result

    - name: Display prune result
      ansible.builtin.debug:
        msg: "{{ prune_result.stdout_lines }}"
      when: docker_action == "prune"

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
      when: docker_action == "start"

    - name: Stop Docker service
      ansible.builtin.service:
        name: docker
        state: stopped
      when: docker_action == "stop"
