---
- name: Package Installation
  hosts: all
  become: true
  gather_facts: true
  vars:
    packages_to_install: []
    packages_to_remove: []
    # Example:
    # packages_to_install:
    #   - vim
    #   - htop
    #   - curl
    
  tasks:
    - name: Install packages (Debian/Ubuntu)
      ansible.builtin.apt:
        name: "{{ packages_to_install }}"
        state: present
        update_cache: yes
      when:
        - ansible_os_family == "Debian"
        - packages_to_install | length > 0

    - name: Install packages (RHEL/CentOS/Fedora)
      ansible.builtin.dnf:
        name: "{{ packages_to_install }}"
        state: present
      when:
        - ansible_os_family == "RedHat"
        - packages_to_install | length > 0

    - name: Remove packages (Debian/Ubuntu)
      ansible.builtin.apt:
        name: "{{ packages_to_remove }}"
        state: absent
        autoremove: yes
      when:
        - ansible_os_family == "Debian"
        - packages_to_remove | length > 0

    - name: Remove packages (RHEL/CentOS/Fedora)
      ansible.builtin.dnf:
        name: "{{ packages_to_remove }}"
        state: absent
      when:
        - ansible_os_family == "RedHat"
        - packages_to_remove | length > 0

    - name: Display installed packages
      ansible.builtin.debug:
        msg: "Installed: {{ packages_to_install | join(,
