---
- name: Security Hardening
  hosts: all
  become: true
  gather_facts: true
  vars:
    ssh_permit_root_login: "prohibit-password"
    ssh_password_auth: "no"
    ssh_port: 22
    
  tasks:
    - name: Configure SSH - Disable password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication {{ ssh_password_auth }}"
        backup: yes
      notify: Restart SSH

    - name: Configure SSH - Root login policy
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin {{ ssh_permit_root_login }}"
      notify: Restart SSH

    - name: Configure SSH - Disable empty passwords
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitEmptyPasswords"
        line: "PermitEmptyPasswords no"
      notify: Restart SSH

    - name: Configure SSH - Use protocol 2 only
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?Protocol"
        line: "Protocol 2"
      notify: Restart SSH

    - name: Set secure permissions on SSH directory
      ansible.builtin.file:
        path: /etc/ssh
        mode: "0755"
        owner: root
        group: root

    - name: Disable core dumps
      ansible.builtin.lineinfile:
        path: /etc/security/limits.conf
        line: "* hard core 0"
        create: yes

    - name: Set secure sysctl parameters
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        state: present
        reload: yes
      loop:
        - { name: "net.ipv4.conf.all.rp_filter", value: "1" }
        - { name: "net.ipv4.conf.default.rp_filter", value: "1" }
        - { name: "net.ipv4.icmp_echo_ignore_broadcasts", value: "1" }
        - { name: "net.ipv4.conf.all.accept_source_route", value: "0" }
        - { name: "net.ipv4.conf.all.send_redirects", value: "0" }
        - { name: "net.ipv4.conf.all.accept_redirects", value: "0" }
        - { name: "net.ipv4.conf.all.log_martians", value: "1" }
        - { name: "net.ipv4.tcp_syncookies", value: "1" }
        - { name: "kernel.randomize_va_space", value: "2" }

    - name: Ensure audit package is installed (RHEL)
      ansible.builtin.dnf:
        name: audit
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure auditd is running
      ansible.builtin.service:
        name: auditd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
