---
- name: Service Management
  hosts: all
  become: true
  gather_facts: false
  vars:
    service_name: ""
    service_action: "status"  # start, stop, restart, reload, enable, disable, status
    
  tasks:
    - name: Validate service name provided
      ansible.builtin.fail:
        msg: "service_name variable must be provided"
      when: service_name == ""

    - name: Get service status
      ansible.builtin.systemd:
        name: "{{ service_name }}"
      register: service_status
      when: service_action == "status"

    - name: Display service status
      ansible.builtin.debug:
        msg: |
          Service: {{ service_name }}
          Active: {{ service_status.status.ActiveState | default("unknown") }}
          Enabled: {{ service_status.status.UnitFileState | default("unknown") }}
          Description: {{ service_status.status.Description | default("N/A") }}
      when: service_action == "status"

    - name: Start service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: started
      when: service_action == "start"

    - name: Stop service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: stopped
      when: service_action == "stop"

    - name: Restart service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted
      when: service_action == "restart"

    - name: Reload service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: reloaded
      when: service_action == "reload"

    - name: Enable service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        enabled: yes
      when: service_action == "enable"

    - name: Disable service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        enabled: no
      when: service_action == "disable"
